analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
  errors:
    # Don't flag TODOs - comment this out when wanting to address
    todo: ignore
    sized_box_for_whitespace: error
    avoid_print: error
    # Causes issues with freezed on CI
    # TODO(brandon): Figure out why this fails on CI only
    # Relevant: https://github.com/rrousselGit/freezed/issues/488
    invalid_annotation_target: ignore
linter:
  rules:
    prefer_expression_function_bodies: false
    public_member_api_docs: false

