name: hydrawise
description: Unopinionated models for use in a program that interacts with the Hydrawise API.
version: 0.0.1
repository: https://github.com/btrautmann/hydrawise-models

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  freezed_annotation: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.8
  freezed: ^2.0.5
  json_serializable: ^6.1.4
  lints: ^1.0.0
  test: ^1.16.0
